{"name": "test_get_user", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 3 validation errors for User\nnickname\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nfirstName\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nlastName\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type", "trace": "@allure.feature('User')\n    @allure.story('Get user')\n    def test_get_user():\n        with allure.step('Get user'):\n            headers = {\n                \"Authorization\": f\"Bearer {login_token()['accessToken']}\",\n                \"Accept\": \"*/*\",\n            }\n            r = requests.get(f\"{USER_SERVICE_URL}users/{valid_user.get('id')}\", headers=headers)\n            response = Response(r)\n            print(response)\n>           response.assert_status_code(200).validate(User)\n\ntests/test_user.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/baseclasses/response.py:17: in validate\n    schema.parse_obj(self.response_json)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'src.schemas.user.User'>\nobj = {'creationDate': '2024-06-02T09:02:05.564059', 'email': 'shina8214@fthcapital.com', 'firstName': None, 'id': 52, ...}\n\n    @classmethod\n    @typing_extensions.deprecated('The `parse_obj` method is deprecated; use `model_validate` instead.', category=None)\n    def parse_obj(cls: type[Model], obj: Any) -> Model:  # noqa: D102\n        warnings.warn(\n            'The `parse_obj` method is deprecated; use `model_validate` instead.', category=PydanticDeprecatedSince20\n        )\n>       return cls.model_validate(obj)\nE       pydantic_core._pydantic_core.ValidationError: 3 validation errors for User\nE       nickname\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.7/v/string_type\nE       firstName\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.7/v/string_type\nE       lastName\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.7/v/string_type\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/main.py:1118: ValidationError"}, "steps": [{"name": "Get user", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 3 validation errors for User\nnickname\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nfirstName\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nlastName\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\n", "trace": "  File \"/Users/alya/shit/tmm/tests/test_user.py\", line 47, in test_get_user\n    response.assert_status_code(200).validate(User)\n  File \"/Users/alya/shit/tmm/src/baseclasses/response.py\", line 17, in validate\n    schema.parse_obj(self.response_json)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/main.py\", line 1118, in parse_obj\n    return cls.model_validate(obj)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/main.py\", line 551, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1717842908900, "stop": 1717842909004}], "start": 1717842908900, "stop": 1717842909005, "uuid": "4d879360-ee15-4f96-a8c8-b59494f6f9fe", "historyId": "e428b259a6a9e608c79a40a0204eef8e", "testCaseId": "e428b259a6a9e608c79a40a0204eef8e", "fullName": "tests.test_user#test_get_user", "labels": [{"name": "feature", "value": "User"}, {"name": "story", "value": "Get user"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "host", "value": "Air-makbuk.Dlink"}, {"name": "thread", "value": "46047-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}